### ISSUE TITLE
pip install fails on Linuxes

### ISSUE THREAD

**Issue by joss13aws** [codycuellar/ultrasequence#1]
'pip install ultrasequence' fails in Linux: 

 pip install ultrasequence
Collecting ultrasequence
  Downloading https://files.pythonhosted.org/packages/52/81/cf26221839c5d0ad3376765ceb94537b97a3c2cbbe835019845cdb3e6b16/ultrasequence-1.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-OBivxL/ultrasequence/setup.py", line 30, in <module>
        long_description=open('readme.rst').read(),
    IOError: [Errno 2] No such file or directory: 'readme.rst'
-------------------------------------------------

I think module is missing that readme.rst from setup.py

**Comment by codycuellar** [comment]
I will implement a fix for this in an upcoming v2 release.
